version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "novelcovid"
      - dependency-name: "twemoji-parser"
      - dependency-name: "sourcebin"
