const Discord = require("discord.js");

const answers = [
  "My wife is really mad at the fact that I have no sense of direction. So I packed up my stuff and right!",
  "How do you get a squirrel to like you? Act like a nut.",
  "Why don't eggs tell jokes? They'd crack each other up.",
  "I don't trust stairs. They're always up to something.",
  "What do you call someone with no body and no nose? Nobody knows.",
  "Did you hear the rumor about butter? Well, I'm not going to spread it!",
  "Why couldn't the bicycle stand up by itself? It was two tired.",
  "Why can't a nose be 12 inches long? Because then it would be a foot.",
  "This graveyard looks overcrowded. People must be dying to get in.",
  "What time did the man go to the dentist? Tooth hurt-y.",
  "How many tickles does it take to make an octopus laugh? Ten tickles.",
  "What concert costs just 45 cents? 50 Cent featuring Nickelback!",
  "How do you make a tissue dance? You put a little boogie in it.",
  "Why did the math book look so sad? Because of all of its problems!",
  "What do you call cheese that isn't yours? Nacho cheese.",
  "What kind of shoes do ninjas wear? Sneakers!",
  "How does a penguin build its house? Igloos it together.",
  "I'm on a seafood diet. I see food and I eat it.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "I made a pencil with two erasers. It was pointless.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Did you hear about the guy who invented the knock-knock joke? He won the 'no-bell' prize.",
  "I've got a great joke about construction, but I'm still working on it.",
  "I used to hate facial hair...but then it grew on me.",
  "I decided to sell my vacuum cleaner—it was just gathering dust!",
  "I had a neck brace fitted years ago and I've never looked back since.",
  "You know, people say they pick their nose, but I feel like I was just born with mine.",
  "What's brown and sticky? A stick.",
  "Why can't you hear a psychiatrist using the bathroom? Because the 'P' is silent.",
  "What do you call an elephant that doesn't matter? An irrelephant.",
  "What do you get from a pampered cow? Spoiled milk.",
  "I like telling Dad jokes. Sometimes he laughs!",
  "Did I tell you the time I fell in love during a backflip? I was heels over head!",
  "If a child refuses to sleep during nap time, are they guilty of resisting a rest?",
  "I ordered a chicken and an egg online. I’ll let you know.",
  "It takes guts to be an organ donor.",
  "If you see a crime at an Apple Store, does that make you an iWitness?",
  "I'm so good at sleeping, I can do it with my eyes closed!",
  "I was going to tell a time-traveling joke, but you guys didn't like it.",
  "It's inappropriate to make a 'dad joke' if you're not a dad. It's a faux pa.",
  "Did you hear about the circus fire? It was in tents.",
  "Can February March? No, but April May!",
  "How do lawyers say goodbye? We'll be suing ya!",
  "Wanna hear a joke about paper? Never mind—it's tearable.",
  "What's the best way to watch a fly fishing tournament? Live stream.",
  "Spring is here! I got so excited I wet my plants.",
  "I could tell a joke about pizza, but it's a little cheesy.",
  "Don't trust atoms. They make up everything!",
  "When does a joke become a dad joke? When it becomes apparent.",
  "I wouldn't buy anything with velcro. It's a total rip-off.",
  "What's an astronaut’s favorite part of a computer? The space bar.",
  "I don't play soccer because I enjoy the sport. I'm just doing it for kicks!",
  "Why are elevator jokes so classic and good? They work on many levels.",
  "Why do bees have sticky hair? Because they use a honeycomb.",
  "What do you call a fake noodle? An impasta.",
  "Which state has the most streets? Rhode Island.",
  "What did the coffee report to the police? A mugging.",
  "What did the fish say when he hit the wall? Dam.",
  "Is this pool safe for diving? It deep ends.",
  "What rock group has four men that don't sing? Mount Rushmore.",
  "When I was a kid, my mother told me I could be anyone I wanted to be. Turns out, identity theft is a crime.",
  "Why do melons have weddings? Because they cantaloupe!",
  "What's the difference between a poorly dressed man on a tricycle and a well-dressed man on a bicycle? Attire!",
  "How many apples grow on a tree? All of them!",
  "Did you hear about the guy who invented Lifesavers?  They say he made a mint!",
  "Last night I had a dream that I weighed less than a thousandth of a gram. I was like, 0mg.",
  "Why did the invisible man turn down the job offer? He couldn't see himself doing it!",
  'I was really angry at my friend Mark for stealing my dictionary. I told him, "Mark, my words!"',
  "How does Moses make his coffee? Hebrews it.",
  "I'm starting a new dating service in Prague. It's called Czech-Mate.",
  "I was just reminiscing about the beautiful herb garden I had when I was growing up. Good thymes.",
  'Why don\'t skeletons ever go trick or treating? Because they have "no body" to go with!',
  "What's ET short for? Because he's only got tiny legs!",
  "What's orange and sounds like a parrot? A carrot!",
  "Why is Peter Pan always flying? He neverlands!",
  "What do Santa's elves listen to ask they work? Wrap music!",
  "Did you hear about the bacon cheeseburger who couldn't stop telling jokes? It was on a roll.",
  "Why was the coach yelling at a vending machine? He wanted his quarter back.",
  "Why do vampires seem sick? They're always coffin.",
  "Where do collge vampire girls like to shop at? Forever 21",
  "Within minutes, the detectives knew what the murder weapon was. It was a brief case.",
  "To whoever stole my copy of Microsoft Office, I will find you. You have my Word!",
  "I used to work in a shoe-recycling shop. It was sole destroying!",
  "My boss told me to have a good day, so I went home!",
  "I thought about going on an all-almond diet… But that's just nuts!",
  "My wife told me I had to stop acting like a flamingo. So I had to put my foot down!",
  "I told my girlfriend she drew her eyebrows too high. She seemed surprised!",
  "I would avoid the sushi if I were you. It's a little fishy!",
  "Five out of four people admit they're bad with fractions!",
  "The difference between a numerator and a denominator is a short line. Only a fraction of people will understand this!",
  "I know a lot of jokes about retired people but none of them work!",
  'Someone complimented my parking today! They left a sweet note on my windshield that said "parking fine."',
  "I found a wooden shoe in my toilet today. It was clogged.",
  "I bought these shoes from a drug dealer. I don't know what he laced them with, but I been tripping all day.",
];

module.exports = {
  name: "dadjoke",
  aliases: "[joke]",
  category: "fun",
  description: "Get a random dadjoke",
  run: async (client, message, args) => {
    return message.reply(
      `${answers[Math.floor(Math.random() * answers.length)]}`
    );
  },
};
